"""Plotting and result-saving helpers for MI experiments."""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from scipy.io import savemat

from myopic_mi.experiment import ExperimentResult


def save_mat_results(result: ExperimentResult, output_file: str | Path) -> Path:
    """Save core numerical arrays to a MATLAB file."""
    path = Path(output_file)
    path.parent.mkdir(parents=True, exist_ok=True)
    savemat(
        path,
        {
            "gamma_list": result.config.gamma_list,
            "T": result.config.horizon,
            "P0": result.initial_covariance,
            "trace_totals": result.trace_totals,
            "trace_paths": result.trace_paths,
            "inst_costs": result.instant_costs,
            "regrets": result.regrets,
            "grid_step": result.config.grid_step,
            "gamma_target": result.config.gamma_target,
        },
    )
    return path


def save_figures(result: ExperimentResult, output_dir: str | Path = "outputs/figures") -> Path:
    """Save the three figures generated by the original script."""
    figure_dir = Path(output_dir)
    figure_dir.mkdir(parents=True, exist_ok=True)
    config = result.config
    gamma_list = config.gamma_list
    gamma_index = int(np.argmin(np.abs(gamma_list - config.gamma_target)))
    t_values = np.arange(1, config.horizon + 1)

    plt.figure(facecolor="white")
    plt.plot(gamma_list, result.trace_totals[0, :], "-o", linewidth=2.5, label=r"$\mathcal{L}^{(1)}$ (Benchmark)")
    plt.plot(gamma_list, result.trace_totals[1, :], "--o", linewidth=2.5, label=r"$\mathcal{L}^{(2)}$")
    plt.plot(gamma_list, result.trace_totals[2, :], "-.o", linewidth=2.5, label=r"$\mathcal{L}^{(3)}$")
    plt.xlabel(r"$\gamma$")
    plt.ylabel("Total cost")
    plt.title(r"Total cost vs $\gamma$ using MI attention")
    plt.legend(loc="best")
    plt.grid(True)
    plt.box(True)
    plt.tight_layout()
    plt.savefig(figure_dir / "figure1_total_cost_vs_gamma.png", dpi=300, bbox_inches="tight")
    plt.close()

    plt.figure(facecolor="white")
    plt.plot(t_values, 100.0 * result.regrets[1, gamma_index, :], "--o", linewidth=2.5, label=r"$\mathcal{L}^{(2)}$")
    plt.plot(t_values, 100.0 * result.regrets[2, gamma_index, :], "-.o", linewidth=2.5, label=r"$\mathcal{L}^{(3)}$")
    plt.xlabel(r"$t$")
    plt.ylabel("Regret (%)")
    plt.title(rf"Regret vs $t$ at $\gamma={config.gamma_target:g}$ using MI attention")
    plt.legend(loc="best")
    plt.grid(True)
    plt.xlim([1, config.horizon])
    plt.box(True)
    plt.tight_layout()
    plt.savefig(figure_dir / "figure2_regret_vs_t_gamma_target.png", dpi=300, bbox_inches="tight")
    plt.close()

    plt.figure(facecolor="white")
    plt.plot(t_values, result.instant_costs[0, gamma_index, :], "-o", linewidth=2.5, label=r"$\mathcal{L}^{(1)}$ (Benchmark)")
    plt.plot(t_values, result.instant_costs[1, gamma_index, :], "--o", linewidth=2.5, label=r"$\mathcal{L}^{(2)}$")
    plt.plot(t_values, result.instant_costs[2, gamma_index, :], "-.o", linewidth=2.5, label=r"$\mathcal{L}^{(3)}$")
    plt.xlabel(r"$t$")
    plt.ylabel("Instant cost")
    plt.title(rf"Instant stage costs vs $t$ at $\gamma={config.gamma_target:g}$ using MI attention")
    plt.legend(loc="best")
    plt.grid(True)
    plt.xlim([1, config.horizon])
    plt.box(True)
    plt.tight_layout()
    plt.savefig(figure_dir / "figure3_instant_cost_vs_t_gamma_target.png", dpi=300, bbox_inches="tight")
    plt.close()
    return figure_dir
